baseURL = "https://jplattel.nl"
publishDir = "docs"
languageCode = "en-us"
title = "Joost Plattel"
theme = "jplattel"
copyright = "Joost Plattel" # cactus will use title if copyright is not set
googleAnalytics = "UA-18951988-1"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Projects"
url = "/project"
weight = 3

[[menu.main]]
name = "Wishlist"
url = "/wishlist"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 6

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 7

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  description = "Iâ€™m Joost Plattel, a data-strategist. I help organizations and individuals develop and build strategies for data-related questions and opportunities."

  # Home page settings
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "02-01-2006" # default

  # Post page settings
  show_updated = false # default

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/jplattel"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/joostplattel"
  [[params.social]]
    name = "instagram"
    link = "https://instagram.com/jplattel"
  [[params.social]]
    name = "github"
    link = "https://github.com/jplattel"
  [[params.social]]
    name = "email"
    link = "jsplattel@gmail.com"  # no need for "mailto:" in the head
  