baseURL = "https://jplattel.nl"
publishDir = "docs"
languageCode = "en-us"
title = "Joost Plattel"
theme = "jplattel"
copyright = "Joost Plattel"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Projects"
url = "/project"
weight = 3

[[menu.main]]
name = "Wishlist"
url = "/wishlist"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 6

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 7

# Output formats for pages
[outputFormats]
  [outputFormats.markdown]
    ugly = true

[outputs]
  page = ["html", "markdown"]
  section = ["html", "rss"]
  home = ["html", "rss"]

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  # Basic
  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default
  description = "Iâ€™m Joost Plattel, I'd like to call myself an auxiliary technologist. I assist organisations and individuals with technology and help them future strategies."

  # Home page settings
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  # the value of name should be an valid font awesome icon name (brands type)
  [[params.social]]
    name = "bluesky"
    link = "https://bsky.app/profile/jplattel.nl"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/joostplattel"
  [[params.social]]
    name = "mastodon"
    link = "https://mastodon.nl/@jplattel"
  [[params.social]]
    name = "instagram"
    link = "https://instagram.com/jplattel"
  [[params.social]]
    name = "github"
    link = "https://github.com/jplattel"
  [[params.social]]
    name = "reddit"
    link = "https://www.reddit.com/user/jplattel"
  [[params.social]]
    name = "goodreads"
    link = "https://www.goodreads.com/user/show/4883795-joost-plattel"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/jplattel"
  [[params.social]]
    name = "email"
    link = "jsplattel@gmail.com"  # no need for "mailto:" in the head
  